### ISSUE TITLE
[question] Assets source

### ISSUE THREAD

**Issue by YDrogen** [tirhande/ixion_planner#23]
Hi! Hope you are well!

I was wondering where did you find all the images of the buildings? I can't seem to find them
Thank you!

Awesome tool you made there! :)

**Comment by tirhande** [comment]
Hi. Thanks.
I extracted the image with a program "Asset Studio" for Unity
github link : [https://github.com/Perfare/AssetStudio/releases](https://github.com/Perfare/AssetStudio/releases)

**Comment by YDrogen** [comment]
Awesome! Thank you! 😄
