### ISSUE TITLE
Issue Placing Steel Mills

### ISSUE THREAD

**Issue by AdeonHawkwood** [tirhande/ixion_planner#31]
When the Steel Mill is oriented so that the entrance is on West side it cannot be placed in the 2 right-most columns or the two bottom-most rows. This bug only occurs in this orientation, other orientations allow for normal placement.
![Steel Mill](https://user-images.githubusercontent.com/52757851/217067649-fe33fc7e-75d3-4e96-842b-61bf24a04b3a.png)

**Comment by tirhande** [comment]
I checked and I will fix it
Thanks

**Comment by tirhande** [comment]
0.65 version is hot fix this bug.
Closing an issue
