### ISSUE TITLE
Wrong Colors for Population, Stability and Food Buildings

### ISSUE THREAD

**Issue by AdeonHawkwood** [tirhande/ixion_planner#43]
The last patch seems to have introduced a bug where Population, Stability and Food Buildings are now the same color as factories rather than the Purple, Blue and Green colors that they were previously.

![Ixion Planner](https://user-images.githubusercontent.com/52757851/221700301-c1480d18-942d-4b32-8d07-72f1f874765e.png)

**Comment by tirhande** [comment]
thanks for finding the issue
the color was duplicated in the process of adding the calculator.

Fixed with patch 0.71 version.

**Comment by AdeonHawkwood** [comment]
Thanks for the fix.
