### ISSUE TITLE
can't put builings behind build menu

### ISSUE THREAD

**Issue by Harachai** [tirhande/ixion_planner#54]
when i am trying to put a mess hall on the lowest row i can't place them because the cursor ends up on the menu and i can't place them with the construction menu gone

**Comment by tirhande** [comment]
> when i am trying to put a mess hall on the lowest row i can't place them because the cursor ends up on the menu and i can't place them with the construction menu gone

Please show me a screenshot.
and what is your monitor resolution?

**Comment by Harachai** [comment]
![IXION Planner — Mozilla Firefox](https://github.com/tirhande/ixion_planner/assets/7036455/698729e9-3837-4b09-82ef-1aa0f32e8fed)
here you go, 1920x1080 resolution. 100% zoom. if it is at 90% zoom i can use it but it doesn't work if i make the window smaller

**Comment by tirhande** [comment]
I slightly reduced the size of the image button.
